application: wtf-clowns
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /media
  static_dir: media

- url: /static
  static_dir: static

- url: .*
  script: myproject.wsgi.application

libraries:
- name: django
  version: 1.5
